export enum ChatEventTypeEnum {
  MEMBER_CREATED = 'member:created',
  MEMBER_UPDATED = 'member:updated',
  MEMBER_CHANGED_STATUS = 'member:changedStatus',
  ROOM_JOINED = 'room:joined',
  ROOM_LEFTED = 'room:lefted',
  MESSAGE_REMOVED = 'message:removed',
  MESSAGE_UPDATED = 'message:updated',
  MESSAGE_CHANGED_STATUS = 'message:changedStatus',
  MESSAGE_CREATED = 'message:created',
  ROOM_DELETED = 'room:deleted',
  ROOM_CREATED = 'room:created',
  ROOM_CLOSED = 'room:closed',
  ROOM_OPENED = 'room:opened',
  ROOM_UPDATED = 'room:updated',
  ROOM_TAGS_ADDED = 'room:tagsAdded',
  ROOM_TAGS_REMOVED = 'room:tagsRemoved',
  ROOMS_UPDATED_BY_TAGS = 'room:updatedByTags',
  ROOMS_DELETED_BY_TAGS = 'room:deletedByTags',
  MEMBER_TYPING = 'member:typing',
  MESSAGES_UNREADED = 'message:unreaded',
}
