export enum ChatWriteRequestTypeEnum {
  MESSAGE_CREATE = 'message:create',
  MESSAGE_UPDATE = 'message:update',
  MESSAGE_REMOVE = 'message:remove',
  MESSAGE_CHANGE_STATUS = 'message:changeStatus',
  MESSAGE_DELIVERED = 'message:delivered',
  MESSAGE_READ = 'message:read',
  MESSAGES_READ = 'messages:read',
  ROOM_JOIN = 'room:join',
  ROOM_LEFT = 'room:left',
  MEMBER_CREATE = 'member:create',
  MEMBER_UPDATE = 'member:update',
  ROOM_CREATE = 'room:create',
  ROOM_CLOSE = 'room:close',
  ROOM_DELETE = 'room:delete',
  ROOM_OPEN = 'room:open',
  MEMBER_CHANGE_STATUS = 'member:changeStatus',
  ROOM_UPDATE = 'room:update',
  ROOM_TAGS_ADD = 'room:tagsAdd',
  ROOM_TAGS_REMOVE = 'room:tagsRemove',
  ROOMS_UPDATE_BY_TAGS = 'room:updateByTags',
  ROOMS_DELETE_BY_TAGS = 'room:deleteByTags',
  MESSAGE_CREATE_WITH_ROOM = 'message:createWithRoom',
}
