export enum SocketEventsEnum {
  CHAT_SERVICE_EXCEPTION = 'ChatService.WebSocket.exception',
  WEB_MESSAGE_CREATE = 'WebAdmin.WebSocket.message.create',
  WEB_MESSAGE_REMOVE = 'WebAdmin.WebSocket.message.remove',
  CHAT_SERVICE_MESSAGE_REMOVED = 'ChatService.WebSocket.message.removed',
  CHAT_SERVICE_MESSAGE_CREATED = 'ChatService.WebSocket.message.created',
  CHAT_SERVICE_MESSAGE_UPDATED = 'ChatService.WebSocket.message.updated',
  CHAT_SERVICE_MESSAGE_CHANGE_STATUS = 'WebSocket.message.changeStatus',
  WEB_ROOMS_CREATE = 'WebAdmin.WebSocket.rooms.create',
  CHAT_SERVICE_ROOMS_CREATED = 'ChatService.WebSocket.rooms.created',
  CHAT_SERVICE_ROOMS_JOINED = 'ChatService.WebSocket.rooms.joined',
  CHAT_SERVICE_ROOMS_LEFT = 'ChatService.WebSocket.rooms.left',
  CHAT_SERVICE_ROOMS_DELETED = 'ChatService.WebSocket.rooms.deleted',
  MEMBER_TYPING = 'WebSocket.member.typing',
  WEB_MESSAGE_DELIVERED = 'WebAdmin.WebSocket.message.delivered',
  CHAT_SERVICE_MESSAGE_UNREAD = 'ChatService.WebSocket.message.unread',
  WEB_MESSAGES_UNREADED = 'WebAdmin.WebSocket.message.unread',
  CHAT_SERVICE_MEMBER_STATUS = 'ChatService.WebSocket.member.status',
  WEB_MESSAGE_READ = 'WebAdmin.WebSocket.message.read',
}
